name: MineCod
main: com.Top_Cat.CODMW.main
version: 0.1
author: Top_Cat
softdepend: [BukkitContrib]
commands:
    r:
        description: Reload bow
    s:
        description: Display score
    team:
        description: Team operations
    vote:
        description: Vote for game options
    y:
        description: Vote yes
    n:
        description: Vote no