name: MineCod
main: com.Top_Cat.CODMW.main
version: 0.2.1
author: Top_Cat
depend: [BukkitContrib]
commands:
    r:
        description: Reload bow
        usage: /<command>
    s:
        description: Display score
        usage: /<command> [d/g]
    team:
        description: Team operations
        usage: /<command> switch
    vote:
        description: Vote for game options
        usage: /<command> [type] [for]
    y:
        description: Vote yes
        usage: /<command>
    n:
        description: Vote no
        usage: /<command>
    auth:
        description: Link minecraft and forum accounts
        usage: /<command> [authcode]
    t:
        description: Team chat
        usage: /<command> message here